spring:
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
#  datasource:
#    url: jdbc:mariadb://mariadb:3306/arbitrage
#    username: root
#    password: arbitrage
#    driver-class-name: org.mariadb.jdbc.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    #    url: -------------------------------develop ?
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/arbitrage
    driver-class-name: org.h2.Driver
    username: sa
    password:
  logging.level:
    org.hibernate:
      sql: debug
      type.descriptor.sql: trace # sql? ????? ? ???
kakao:
  url:
    sendme: https://kapi.kakao.com/v2/api/talk/memo/default/send
    oauth: https://kauth.kakao.com/oauth/token
    sendfriend: https://kapi.kakao.com/v1/api/talk/friends/message/default/send
  key:
    restapi: 7ea74159c7a47e8845cd28547f145243